### ISSUE TITLE
Mixed up step numbering in new lab 12

### ISSUE THREAD

**Issue by VitalyMCT** [MicrosoftLearning/mslearn-ai-fundamentals#40]
https://github.com/MicrosoftLearning/mslearn-ai-fundamentals/blob/main/Instructions/Labs/12-generative-ai.md

Step numbering unexpectedly gets reset back to 1 in several places in this lab due to Markdown issues. This makes it hard to use step numbers for reference and troubleshooting during classes. Please fix.

**Comment by sherzyang** [comment]
Thanks @VitalyMCT , I fixed the numbering issue

**Comment by VitalyMCT** [comment]
Still broken in at least 1 place:

<img width="1101" alt="Image" src="https://github.com/user-attachments/assets/a352b9e4-803a-41c5-a586-a96154bd135e" />
